modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"
issueTrackerURL="https://github.com/IGieckI/ComboCraft/issues"

[[mods]]
modId="igieckicombocraft"
version="1.0.0"
displayName="ComboCraft"
displayURL="https://github.com/IGieckI/ComboCraft"
authors="IGieckI"
description="To-do"

[[dependencies.igieckicombocraft]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.igieckicombocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"